// West Maui Chocolatier — Japan site data
window.WMC_DATA = {
  products: [
    {
      id: "signature-bonbons-12",
      collection: "bonbon",
      jp: "シグネチャー・ボンボン 12粒",
      en: "Signature Bonbon Collection",
      jpSub: "12粒入り",
      tagline: "宝石のような12粒。マウイの色彩を一箱に。",
      price: 6800,
      tags: ["best", "gift"],
      img: "assets/bonbon-box-monstera.png",
      gallery: ["assets/bonbon-box-monstera.png", "assets/bonbon-grid-boxes.png", "assets/bonbons-yellow-green.png", "assets/moon-bonbon.png"],
      desc: "ハワイ産カカオを軸に、リリコイ（パッションフルーツ）、コナコーヒー、海塩キャラメルなど、マウイの恵みを12種類のガナッシュに閉じ込めました。一粒ごとに手描きされたカカオバターは、世界に一つとして同じものがありません。",
      specs: {
        "原材料": "カカオ豆（ハワイ・エクアドル）、生クリーム（北海道）、リリコイ、コナコーヒー、カウアイ島産海塩、有機甘蔗糖",
        "内容量": "12粒（約140g）",
        "賞味期限": "発送日より14日",
        "保存方法": "16〜18℃の冷暗所",
        "アレルゲン": "乳・大豆（一部の粒に：卵・くるみ）",
        "配送": "クール便（ヤマト運輸）",
      },
      options: { size: ["6粒 ¥3,800", "12粒 ¥6,800", "24粒 ¥12,800"], wrap: ["なし", "ギフト包装 +¥500", "風呂敷包み +¥1,500"] },
      rating: 4.9, reviews: 248,
    },
    {
      id: "lilikoi-bonbon",
      collection: "bonbon",
      jp: "リリコイ ガナッシュ ボンボン",
      en: "Lilikoi Ganache Bonbon",
      jpSub: "9粒入り",
      tagline: "南国の太陽を凝縮した、黄金色の一粒。",
      price: 5400,
      tags: ["new"],
      img: "assets/lilikoi-bonbon-tray.png",
      gallery: ["assets/lilikoi-bonbon-tray.png", "assets/lilikoi-stringing.png", "assets/lilikoi-ganache.png"],
      desc: "ハワイの太陽を浴びて育ったリリコイ（パッションフルーツ）の果汁を贅沢に使った、爽やかな酸味のガナッシュ。バニラと海塩マシュマロのレイヤーが、香りに奥行きを与えます。",
      specs: {
        "原材料": "ホワイトチョコレート、リリコイ果汁、生クリーム、バニラ、カウアイ島産海塩、卵白",
        "内容量": "9粒（約105g）",
        "賞味期限": "発送日より10日",
        "保存方法": "10〜18℃の冷暗所",
        "アレルゲン": "乳・卵・大豆",
      },
      options: { size: ["6粒 ¥3,600", "9粒 ¥5,400", "16粒 ¥9,600"], wrap: ["なし", "ギフト包装 +¥500"] },
      rating: 4.8, reviews: 92,
    },
    {
      id: "geode-hearts",
      collection: "heart",
      jp: "ジオード・ハート 4種",
      en: "Geode Heart Quartet",
      jpSub: "4個入り",
      tagline: "原石のような輝き。割って楽しむ大粒のハート。",
      price: 4800,
      tags: ["gift", "valentine"],
      img: "assets/gold-hearts-boxed.png",
      gallery: ["assets/gold-hearts-boxed.png", "assets/hearts-marble.png", "assets/mold-hearts-red.png"],
      desc: "幾何学的な多面体に削り出された大粒のハートチョコレート。表面には24金の金箔とエアブラシで描かれた色彩。中にはマウイの果実とミルクチョコレートのガナッシュが詰まっています。",
      specs: {
        "原材料": "カカオ豆、生クリーム、グアバ、マンゴー、24金箔、有機甘蔗糖",
        "内容量": "4個（約180g）",
        "賞味期限": "発送日より14日",
        "アレルゲン": "乳・大豆",
      },
      options: { size: ["2個 ¥2,800", "4個 ¥4,800", "6個 ¥7,200"], wrap: ["なし", "ギフト包装 +¥500", "風呂敷包み +¥1,500"] },
      rating: 5.0, reviews: 156,
    },
    {
      id: "kauai-truffles",
      collection: "truffle",
      jp: "カウアイ海塩 生トリュフ",
      en: "Kauai Sea Salt Truffles",
      jpSub: "16粒入り",
      tagline: "口溶けの記憶を、マウイの夜風と共に。",
      price: 4200,
      tags: ["best"],
      img: "assets/truffles-glass.png",
      gallery: ["assets/truffles-glass.png", "assets/sea-salt-kauai.png"],
      desc: "70%カカオの生チョコレートに、カウアイ島で天日塩されたフレーク状の海塩を効かせました。一粒口に含むと、ココアパウダーの粉雪が解け、塩のミネラルが甘さを引き立てます。",
      specs: {
        "原材料": "カカオ豆、生クリーム、無塩バター、カウアイ島産海塩、ココアパウダー",
        "内容量": "16粒（約180g）",
        "賞味期限": "発送日より7日（要冷蔵）",
        "保存方法": "10℃以下の冷蔵",
        "アレルゲン": "乳",
      },
      options: { size: ["8粒 ¥2,400", "16粒 ¥4,200", "32粒 ¥7,800"], wrap: ["なし", "ギフト包装 +¥500"] },
      rating: 4.9, reviews: 312,
    },
    {
      id: "macadamia-bar",
      collection: "bar",
      jp: "マカダミア ブロック",
      en: "Macadamia Block",
      jpSub: "3個入り",
      tagline: "ハワイ産マカダミアナッツの、噛みしめる時間。",
      price: 3200,
      tags: [],
      img: "assets/macadamia-bars.png",
      gallery: ["assets/macadamia-bars.png"],
      desc: "ハワイ島産マカダミアナッツをまるごと閉じ込めた厚切りブロック。ミルクチョコレートのコクとナッツの香ばしさが、コーヒーや日本茶のお供に。",
      specs: {
        "原材料": "カカオ豆、ハワイ産マカダミアナッツ、全粉乳、有機甘蔗糖",
        "内容量": "3個（1個約45g）",
        "賞味期限": "発送日より30日",
        "アレルゲン": "乳・木の実類",
      },
      options: { size: ["3個 ¥3,200", "6個 ¥6,000"], wrap: ["なし", "ギフト包装 +¥500"] },
      rating: 4.7, reviews: 78,
    },
    {
      id: "moon-bonbon",
      collection: "bonbon",
      jp: "ムーン ボンボン",
      en: "Crescent Moon Bonbon",
      jpSub: "限定",
      tagline: "三日月の夜、マウイの空を一粒に。",
      price: 1800,
      tags: ["limited"],
      img: "assets/moon-bonbon.png",
      gallery: ["assets/moon-bonbon.png"],
      desc: "三日月の形にかたどった、限定のシトラス＆ハニーガナッシュ。星空のような銀箔をまとった一粒です。",
      specs: {
        "原材料": "ホワイトチョコレート、ハワイ産はちみつ、レモン、銀箔",
        "内容量": "1粒（約14g）",
        "賞味期限": "発送日より10日",
        "アレルゲン": "乳",
      },
      options: { size: ["1粒 ¥1,800", "3粒 ¥5,200"], wrap: ["桐箱 +¥800"] },
      rating: 5.0, reviews: 42,
    },
    {
      id: "easter-egg",
      collection: "egg",
      jp: "アロハ・エッグ",
      en: "Aloha Painted Egg",
      jpSub: "シーズン限定",
      tagline: "手描きのカカオバターで一つひとつ彩られた、卵型のチョコレート。",
      price: 5800,
      tags: ["limited"],
      img: "assets/easter-egg-painted.png",
      gallery: ["assets/easter-egg-painted.png", "assets/easter-eggs-pastel.png", "assets/easter-eggs-tray.png"],
      desc: "手のひらサイズのチョコレートエッグ。中には小粒のボンボンが詰まったサプライズボックス。割る瞬間まで、何が出てくるかは秘密です。",
      specs: {
        "原材料": "カカオ豆、生クリーム、各種フィリング、カカオバター（着色用）",
        "内容量": "1個（約220g）",
        "賞味期限": "発送日より14日",
        "アレルゲン": "乳・大豆",
      },
      options: { size: ["S ¥5,800", "L ¥9,800"], wrap: ["なし", "ギフト包装 +¥500"] },
      rating: 4.9, reviews: 64,
    },
    {
      id: "tasting-flight",
      collection: "set",
      jp: "テイスティング・フライト",
      en: "Tasting Flight",
      jpSub: "8種セット",
      tagline: "マウイの全てを、ひと箱で。",
      price: 8800,
      tags: ["best", "gift"],
      img: "assets/bonbon-grid-boxes.png",
      gallery: ["assets/bonbon-grid-boxes.png", "assets/bonbons-yellow-green.png"],
      desc: "シグネチャーボンボン、生トリュフ、ハート、マカダミアブロックを少しずつ。初めての方への贈り物にも、ご自身へのご褒美にもおすすめのアソートメントです。",
      specs: {
        "内容": "ボンボン4粒 / 生トリュフ4粒 / ハート2個 / マカダミア2個",
        "賞味期限": "発送日より7日（要冷蔵）",
        "アレルゲン": "乳・大豆・木の実類",
      },
      options: { size: ["スタンダード ¥8,800", "プレミアム ¥14,800"], wrap: ["ギフト包装 標準", "風呂敷包み +¥1,500"] },
      rating: 4.9, reviews: 188,
    },
  ],

  giftScenes: [
    { id: "valentine", jp: "バレンタイン", en: "Valentine", img: "assets/hearts-marble.png", line: "想いを、形にして。", price: "¥4,800〜" },
    { id: "celebration", jp: "お祝い・記念日", en: "Celebration", img: "assets/gold-hearts-boxed.png", line: "金色の祝福を一箱に。", price: "¥6,800〜" },
    { id: "thanks", jp: "感謝・お礼", en: "Gratitude", img: "assets/bonbon-box-monstera.png", line: "言葉以上の、丁寧な気持ち。", price: "¥3,800〜" },
    { id: "wedding", jp: "結婚・引き出物", en: "Wedding", img: "assets/lilikoi-bonbon-tray.png", line: "二人の門出に、太陽の色を。", price: "個別見積" },
    { id: "corporate", jp: "法人・接待", en: "Corporate", img: "assets/tabletop-display.png", line: "格別な席に、格別な甘さを。", price: "¥10,000〜" },
    { id: "self", jp: "自分への贈り物", en: "Self-Care", img: "assets/truffles-glass.png", line: "今夜、グラスと一緒に。", price: "¥2,400〜" },
  ],

  reviews: [
    { name: "M.K. 様", area: "東京都・40代女性", text: "封を開けた瞬間に広がる果実の香り。一粒ひとつぶに物語があって、家族みんなで「これは何の味？」と当てっこしながらいただきました。", stars: 5 },
    { name: "Y.S. 様", area: "大阪府・50代男性", text: "海外出張の手土産に。受け取った相手が「こんな美しいチョコは初めて」と。間違いのない品です。", stars: 5 },
    { name: "A.T. 様", area: "神奈川県・30代女性", text: "リリコイの香りに本当に驚きました。マウイに行きたくなる味。", stars: 5 },
  ],

  timeline: [
    { yr: "2014", title: "マウイの小さな工房から", desc: "創業者・Yuriが、ハワイ・マウイ島ラハイナの自宅キッチンでひとりチョコレート作りを始める。", img: "assets/founder-studio.png" },
    { yr: "2017", title: "Kamananui Cacao Orchards との出会い", desc: "オアフ島のカカオ農園と独占契約。Bean to Bar の哲学が確立する。", img: "assets/cacao-orchard.png" },
    { yr: "2020", title: "受賞、そしてマウイ山火事", desc: "International Chocolate Awards 銀賞受賞。同年、マウイ山火事で工房を一時閉鎖。地域復興に取り組む。", img: "assets/maui-park-sign.png" },
    { yr: "2024", title: "ボンボン・コレクション誕生", desc: "宝石のように手描きされたボンボンシリーズが世界中のメディアで話題に。", img: "assets/bonbons-yellow-green.png" },
    { yr: "2026", title: "日本上陸", desc: "東京・銀座にショールーム&テイスティングサロンを開設。日本市場向け公式オンラインストア launch。", img: "assets/tabletop-display.png" },
  ],

  ingredients: [
    { en: "Hawaiian Cacao", jp: "ハワイ産カカオ", img: "assets/cacao-orchard.png", text: "オアフ島 Kamananui Cacao Orchards より。火山性土壌で育つカカオは、ハワイ独特の花の香りと低い苦味を持ちます。収穫から発酵までを農園で行い、空輸でマウイ島の工房へ。" },
    { en: "Lilikoi", jp: "リリコイ（パッションフルーツ）", img: "assets/lilikoi-ganache.png", text: "マウイの太陽を浴びて熟したリリコイ。果汁の酸味と熱帯の香りは、ホワイトチョコレートやガナッシュとの相性抜群。1日で使い切れる分だけ毎朝仕込みます。" },
    { en: "Kauai Sea Salt", jp: "カウアイ島産 海塩", img: "assets/sea-salt-kauai.png", text: "カウアイ島の太平洋岸で天日塩されたフレーク塩。ミネラルの複雑な味わいが、チョコレートの甘味の奥行きを引き出します。" },
    { en: "Maui Macadamia", jp: "マウイ産 マカダミア", img: "assets/macadamia-bars.png", text: "ハワイ島の自社契約農家より仕入れる、ロースト直後のマカダミアナッツ。香ばしさと食感を最大限に活かすため、刻まずまるごと使用します。" },
  ],

  faqs: [
    { q: "賞味期限はどのくらいですか？", a: "商品により7日〜30日です。生トリュフ・ガナッシュ系は要冷蔵で7〜10日、ボンボン・ハート系は常温で14日、ブロック系は30日が目安です。各商品ページにてご確認ください。" },
    { q: "配送方法・送料を教えてください。", a: "ヤマト運輸クール便（一部商品はネコポス）でお届けします。送料は本州・四国 ¥980、九州・北海道 ¥1,480、沖縄 ¥1,980。¥10,000 以上のご注文で全国送料無料です。" },
    { q: "ギフト包装はできますか？", a: "全商品でギフト包装（+¥500）、人気のボンボン・ハート・セット商品では風呂敷包み（+¥1,500）にも対応しています。メッセージカード（無料）もお付けできます。" },
    { q: "アレルギー表示について。", a: "全商品のアレルゲン情報を商品詳細ページに記載しています。同一工房内で乳・卵・大豆・木の実類を扱っているため、コンタミネーションの可能性があります。" },
    { q: "海外発送は可能ですか？", a: "現在、日本国内のみの発送です。海外発送ご希望の場合は CONTACT より個別にお問い合わせください。" },
    { q: "実店舗はありますか？", a: "東京・銀座にショールーム&テイスティングサロン（完全予約制）がございます。マウイ島本店は Lahaina に再オープン予定です。" },
    { q: "法人ギフト・大量注文は対応していますか？", a: "100点以上の法人・ウェディング向けロット注文を承っております。専用ページよりお見積りをご依頼ください。" },
    { q: "定期便はありますか？", a: "「マンスリー・マウイ便」として、毎月異なるテーマの12粒を月替わりでお届けする定期便（¥5,800/月、いつでも休止可）をご用意しています。" },
  ],
};
